services:

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: el_gabacho
    volumes:
      - ./data:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-app
    depends_on:
      - db
    ports:
      - "5000:5000"