services:

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: el_gabacho
    volumes:
      - ./data:/var/lib/mysql                  # Volumen persistente para los datos de la base de datos
      - ./initdb:/docker-entrypoint-initdb.d   # Carpeta para archivos SQL iniciales, solo para la primera vez

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-app
    depends_on:
      - db
    ports:
      - "5000:5000"